//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitNotificaion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBUser
    {
        public FBUser()
        {
            this.LinkPosts = new HashSet<LinkPost>();
        }
    
        public string FBID { get; set; }
        public string ELUsername { get; set; }
        public string ULPassword { get; set; }
    
        public virtual ICollection<LinkPost> LinkPosts { get; set; }
    }
}
