//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitNotificaion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkPost
    {
        public LinkPost()
        {
            this.Posts = new HashSet<Post>();
            this.FBUsers = new HashSet<FBUser>();
        }
    
        public string HrefTrack { get; set; }
        public string Tittle { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<FBUser> FBUsers { get; set; }
    }
}
